### ISSUE TITLE
typo in test.js

### ISSUE THREAD

**Issue by brdauria** [IndigoUnited/node-promptly#17]
Do you want to test {silent:true} or {silent:false}?
 it('should write input to stdout if silent is false', function (next) {
        promptly.prompt('something: ', { silent: true }, function (err, value) {
            expect(err).to.be(null);
            expect(value).to.be('yeaa');
            expect(stdout).to.contain('something: ');
            expect(stdout).to.not.contain(value);
            next();
        });

**Comment by satazor** [comment]
The test name is wrong, should be `if true`. Can you please do a pull request?

**Comment by brdauria** [comment]
done. Regards

**Comment by satazor** [comment]
Fixed in https://github.com/IndigoUnited/node-promptly/commit/de4a099c8776ec526e64d1f184f4699974a300e7

See my comment on the PR.
